apiVersion: v1
kind: Namespace
metadata:
  name: enhanced-ids
  labels:
    name: enhanced-ids
    purpose: intrusion-detection-system
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ids-resource-quota
  namespace: enhanced-ids
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
