apiVersion: v1
kind: PersistentVolume
metadata:
  name: ids-models-pv
  labels:
    app: enhanced-ids
    type: models
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/ids/models
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ids-logs-pv
  labels:
    app: enhanced-ids
    type: logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/ids/logs
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ids-data-pv
  labels:
    app: enhanced-ids
    type: data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/ids/data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ids-models-pvc
  namespace: enhanced-ids
  labels:
    app: enhanced-ids
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      type: models

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ids-logs-pvc
  namespace: enhanced-ids
  labels:
    app: enhanced-ids
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      type: logs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ids-data-pvc
  namespace: enhanced-ids
  labels:
    app: enhanced-ids
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      type: data
